### ISSUE TITLE
ATC

### ISSUE THREAD

**Issue by igorboss** [TEHIK-EE/terminology-migration#10]
What is real source of ATC EE?
Does we need concepts in CS? 
Options:
1) May it will be better to have external code system and real data will be in Ravimiamet?
2) If data will be in terminology server the who and how often will refresh them? Which versioning approach will be used?

**Comment by rlindstrm** [comment]
ATC is currently not published in publitseerimiskeskus. This is not in the first wave of migration.
When we migrate it (later), we will create local codesystem for Estonian ATC, the source is Ravimiamet and there will have to be a service that updates it automatically via Ravimiregister.
A starter pack with all the deprecated codes must be retrieved from Ravimiamet's internal system.
In short: ignore it for now.
