### ISSUE TITLE
Health Insurance Fund price list

### ISSUE THREAD

**Issue by rlindstrm** [TEHIK-EE/terminology-migration#11]
Eesti Haigekassa tervishoiuteenuste hinnakiri

Started negotiation/analysis whether we can stop publishing prices. The part that looks more like terminology will be published, because it has been used for documenting, and it is often needed for mappings. 

Will be in the agenda of terminology coordination group next week.

**Comment by igorboss** [comment]
EHIF services imported into https://termx.kodality.dev/resources/code-systems/ehif-service/versions/1.0.0/concepts CS. Please review it.
