### ISSUE TITLE
calculatable properties

### ISSUE THREAD

**Issue by igorboss** [TEHIK-EE/terminology-migration#17]
This issue lists the property candidates that should support expressions and may be calculated during import:

- notSelectable. Type: boolean. Should it be expressed as expression: a la "if vanem or is-a or parent or groupedBy is null then true else false"? Or this info should be a part of the input classifier?
- inactive. Type: boolean. Should it be calculated through the expression: a la "if retirementDate < today() or staatus=0 then true else false"?
- status. Type: code. Should it be calculated through the expression: a la "if retirementDate < today() or staatus=0 then 'retired' else 'active'"?

**Comment by rlindstrm** [comment]
notSelectable: ignore for the first iteration. Only applicable for certain value sets / supplements.
inactive and status: yes. Do we need all three properties for communicating retired concepts or choose one?

**Comment by igorboss** [comment]
- inactive and status are alternatives. Mapping: inactive=true <-> status=retired, anactive=false<->status=active. Status gives more options, for example, statuses: draft, deleted, but inactive give more possibility to use expressions (it may based on status, retirementDate, etc). So it is a strategical decision.

**Comment by rlindstrm** [comment]
So technically it would be smart to have all three? Or shall we skip the retirementDate (which is the most trustworthy one in current import files).

**Comment by igorboss** [comment]
1. We have status internally anyway. Status may be shown in FHIR API. Just add "status" property to the CS definition.
2. retirementDate and inactive is additional possibilities. In the case of CS they are just informative properties. Both are presented in the list of defined properties and may be used.
