### ISSUE TITLE
Otsusetoe rakenduse EBMEDS RHK-10 diagnooside filter

### ISSUE THREAD

**Issue by igorboss** [TEHIK-EE/terminology-migration#18]
EBMEDS diagnosis filter contains very specific XML input https://pub.e-tervis.ee/classifications/Otsusetoe%20rakenduse%20EBMEDS%20RHK-10%20diagnooside%20filter/2.

It was converted manually to the TEXT [file](https://github.com/TEHIK-EE/terminology-migration/files/12429129/dssDiagnoses.txt).

Otherwise, the creation of the value set failed because it contains duplicates: H83.0, F32.10, F10.2. Duplicates were removed manually (and still in the attached file). The results of the import are available [here](https://termx.kodality.dev/api/fhir/ValueSet/ebmeds-diagnooside-filter@2/$expand?includeDesignations=true&displayLanguage=et).

**Comment by rlindstrm** [comment]
EBMEDS has two filters. Both are still waiting for a decision what to do with them.
