### ISSUE TITLE
ER_Müügiloata taotluse põhjendus

### ISSUE THREAD

**Issue by igorboss** [TEHIK-EE/terminology-migration#19]
Classifier https://pub.e-tervis.ee/classifications/ER_Müügiloata%20taotluse%20põhjendus/1 have three text columns (lühinimetus, nimetus, pikk_nimetus) and all of them are equals and in the same language.
How many designations should be in the code system?
Currently it migrated as one designation https://termx.kodality.dev/api/fhir/CodeSystem/er-myygiloata-taotluse-pohjendus@1.0.0 .

**Comment by rlindstrm** [comment]
I think one is enough for these cases.

**Comment by igorboss** [comment]
Actually, it means that every classifier should be reviewed manually and for every classifier we should decide which columns should be imported. The review is needed in any case because sometimes "Pikk_nimetus" contains Estonian designations and sometimes English designations. Sometimes we need should create a code system and a value set and sometimes only a value set.

**Comment by rlindstrm** [comment]
It's ok to look them through, but I don't know how to document it. Can you think of a format for that?

**Comment by rlindstrm** [comment]
@igorboss 
Have you considered the document format we could use for this listing/mapping?
If I could create that for you (or have some people working on it), we could maybe advance significantly faster than going through asking one by one.
The table should also then give an opportunity to adjust metadata (id-s and names) in case the automatic ones don't work.
Think about it, then let's have a call.

**Comment by igorboss** [comment]
Still waiting for input data from @ScharlettH 
`
Ekspordi oleks vaja https://pub.e-tervis.ee/classifications lehel ja alamlehtedel nähtavat informatsiooni masintöödeldaval kujul (csv, json, xml (või SQL insert laused)).
Tunnused (https://pub.e-tervis.ee-st)
/classifications - kaust, kirjeldus
/classifications/$kaust - Kirjeldusfail (failina või base64), OID, viimase versiooni number, viimase versiooni kirjeldus
/classifications/$kaust/$versioon - staatus, CSV faili sisu (failina või base64)
`
The following steps are: 1) add machine processable "id"; 2) create a list of all possible columns; 3)specify a list of migratable columns (their types and languages); 4) specify what resources should be created (cs, cs-suplement, vs); 5) specify which resources should be created (semi)manually;

**Comment by ScharlettH** [comment]
Latest it will be available on Monday afternoon :)
