### ISSUE TITLE
SNOMED based classifiers

### ISSUE THREAD

**Issue by igorboss** [TEHIK-EE/terminology-migration#20]
SNOMED based classifiers in the Pubkeskus (like https://pub.e-tervis.ee/classifications/Farmakogeneetilise%20uuringu%20(geeniprodukti%20funktsioon)%20vastus/2) typically have both Estonian name and English FSN name.
Should we migrate these names and add them to include rule?
Or we will include only codes and names will be populated from SNOMED server?

The example of valueset where names added to include rule is: https://termx.kodality.dev/api/fhir/ValueSet/geeniprodukti-funktsioon@2/$expand?includeDesignations=true&displayLanguage=et
Non SNOMED example where included only codes and designations are in expansion: https://termx.kodality.dev/api/fhir/ValueSet/ebmeds-diagnooside-filter@2/$expand?includeDesignations=true&displayLanguage=et

**Comment by rlindstrm** [comment]
Display names have to be populated from the file (usually Nimetus, but for lab, it's sometimes Lühinimetus - it's written in the metadata file (Selgitusfail) which one is meant to be used in data exchange. 
FSNs and Estonian preferred terms can be populated from SNOMED codesystem on the server.

(what a chaos)
