### ISSUE TITLE
Non-standard non-CSV classifiers

### ISSUE THREAD

**Issue by igorboss** [TEHIK-EE/terminology-migration#23]
The list of non-standard classifiers:
~~~
"standard_id";"standard_name";"version_name";"formats"
1562;Keelte Klassifikaator;"1.0";txt,xls,xml
1582;RHK-10;"9";pdf,pdf,zip,zip
1736;Ametite Klassifikaator;"3";txt,xls,xml
28562;Laborianalüüsid Eestis LOINC;"3";
47728;Otsusetoe rakenduse EBMEDS mõõtmiste filter;"1";xml
47730;Otsusetoe rakenduse EBMEDS RHK-10 diagnooside filter;"2";xml
49107;Analüüsiseadme identifikaator JRC järgi;"1";
~~~

The current state:
- ICD10 - [solved](https://github.com/TEHIK-EE/terminology-migration/issues/1)
- Ametite Klassifikaator - [solved](https://github.com/TEHIK-EE/terminology-migration/issues/12)
- Keelte Klassifikaator - [AllLanguages](http://hl7.org/fhir/ValueSet/all-languages) valueset should be used instead? At the same time [KK](https://pub.e-tervis.ee/classifications/KK/1.0) and BCP 47 language tag is a standardized code or tag that is used to identify human languages in the Internet (a language code) are not overlap. The question is about usage of KK.
- Otsusetoe rakenduse EBMEDS RHK-10 diagnooside filter - [solved](https://termx.kodality.dev/resources/value-sets/ebmeds-diagnooside-filter/summary) through manual import
- LOINC - should be imported as external code system?
- [Otsusetoe rakenduse EBMEDS mõõtmiste filter](https://pub.e-tervis.ee/classifications/Otsusetoe%20rakenduse%20EBMEDS%20mõõtmiste%20filter/1) - who and how use it? It may be migrated (manually) from XML to CSV and then migrated as regular code system to the supplement code system that based on LOINC with 2 parameters MaxAgeInYears and MaxObservations.
- [Analüüsiseadme identifikaator JRC järgi](https://pub.e-tervis.ee/classifications/Analüüsiseadme%20identifikaator%20JRC%20järgi) - does we need it at all?

**Comment by igorboss** [comment]
[Otsusetoe rakenduse EBMEDS mõõtmiste filter](https://pub.e-tervis.ee/classifications/Otsusetoe%20rakenduse%20EBMEDS%20m%C3%B5%C3%B5tmiste%20filter/1) will be out of scope.

**Comment by rlindstrm** [comment]
Open topics:
Keelte klassifikaator #52 
EBMEDS filters (separate issue) #18 
LOINC (separate issue) #51 
Analüüsiseadme identifikaator JRC järgi #53
