### ISSUE TITLE
First batch migration issues/questions

### ISSUE THREAD

**Issue by rlindstrm** [TEHIK-EE/terminology-migration#25]
I'm not feeling smart at all, so these are questions and a reflection of my inner confusion.

1) Should they be requestable from TermX server? I did not manage. 'https://termx.kodality.dev/api/fhir/CodeSystem/abivahendid-funktsioonide-toetamiseks--1' resulted in 403 "abivahendid-funktsioonide-toetamiseks.CodeSystem.read not allowed"

2) Should the CS or VS id always contain version number? It does right now.

3) All dates include date and time, but I'm not sure we want time. "date": "2016-05-27T00:00:00Z" is maybe reasonable to have time, but effectiveDates would probably look cleaner without time. 

4) ValueSet using codesystem supplement. SNOMED has property "parent". With supplement we assigned new parents. The value set expansion seems to include the correct parents, but I don't know why.  If the base SNOMED and supplement both assign parents, shouldn't it take all parents from both? I assumed it would and suggested GroupedBy attribute rather than "parent", so I am a little confused why it seems to work with just "parent". Is it because you have pre-defined the expansion? Isn't that risky? 

5) Hierachy meaning by default is is-a. Should I correct manually when I want something else? "https://fhir.ee/CodeSystem/apgari-komponendid" for example clearly has grouped-by (changed it in TermX, but not sure if that is the best way to go).

**Comment by rlindstrm** [comment]
6. I've managed to mix up Terviseamet and Tervisekassa as endorser for all the ER_... value sets. Should I fix in the file or manually or both?

**Comment by rlindstrm** [comment]
7. Display seems to be listed as one of the properties in json. I'm not sure that's correct.
8. Right now, the language of the CS resource is the default language of any display name that is used in the CS. Is that sufficient, or should every display name also have a language tag? Just in case we would have more languages per one code some time in the future.

**Comment by igorboss** [comment]
1. We reconfigured server and by default  access is profibited to the all CS and VS. Please authorize first, I'll reconfigure server later.
2. Yes, version number should be in the id. The Ontoserver use uuid for that, but I think that combination of CS/VS+version is more informative.
3.  Depends on datatype. Most datetime/timestamp requires TZ also.
4,5,6.  Lets discuss it on Monday.
7. This is decision point. We can made it configurable.
8. Yes, every display have own language tag. You can changed preferred language for every version.

**Comment by rlindstrm** [comment]
4. for further testing, also in Ontoserver
5. fix manually, mark a comment in table
6. fix in table
