### ISSUE TITLE
Import error: CS abivahendid-ja-meditsiiniseadmed

### ISSUE THREAD

**Issue by marinaivnv** [TEHIK-EE/terminology-migration#26]
Import to **TermX** succeeded: [abivahendid-ja-meditsiiniseadmed](https://termx.kodality.dev/fhir/CodeSystem/abivahendid-ja-meditsiiniseadmed--4?tab=json).

Import to **Ontoserver** errors: 
- CodeSystems SHOULD NOT have a stated value for the hierarchyMeaning element when they are a supplement
- The code '182587004' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement
- The code '183135000' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement
- The code '224898003' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement
- The code '257192006' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement
- The code '277973009' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement
- The code '303476002' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement
- The code '3611000181101' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement
- The code '6012004' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement
- The code '705330007' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement
- The code '705332004' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement
- The code '705371001' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement
- The code '705383004' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement
- The code '705413009' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement
- The code '74964007' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement

**Comment by rlindstrm** [comment]
Remove hierachy-meaning.
Replace property "parent" with "groupedBy".
Specific CS version needed: "supplements": "http://snomed.info/sct|http://snomed.info/sct/11000181102/version/20230530"
