### ISSUE TITLE
Import error: CS antibiootikumtundlikkus

### ISSUE THREAD

**Issue by marinaivnv** [TEHIK-EE/terminology-migration#27]
Import to **TermX** succeeded: [antibiootikumtundlikkus](https://termx.kodality.dev/fhir/CodeSystem/antibiootikumtundlikkus--5?tab=json).

Import to **Ontoserver** errors: 
- The code '131196009' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement
- The code '280416009' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement
- The code '30714006' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement
- The code '601000181101' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement

**Comment by rlindstrm** [comment]
Specific CS version needed:
"supplements": "http://snomed.info/sct|http://snomed.info/sct/11000181102/version/20230530",
