### ISSUE TITLE
Import error: CS kvalitatiivse-uuringu-vastus

### ISSUE THREAD

**Issue by marinaivnv** [TEHIK-EE/terminology-migration#28]
Import to **TermX** succeeded: [kvalitatiivse-uuringu-vastus](https://termx.kodality.dev/fhir/CodeSystem/kvalitatiivse-uuringu-vastus--7?tab=json).

Import to **Ontoserver** errors: 
- The code '10828004' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement
- The code '14761000181107' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement
- The code '260347006' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement
- The code '260348001' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement
- The code '260349009' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement
- The code '260350009' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement
- The code '260385009' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement
- The code '280416009' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement
- The code '371932001' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement
- The code '720735008' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement

**Comment by rlindstrm** [comment]
Specific CS version needed:
"supplements": "http://snomed.info/sct|http://snomed.info/sct/11000181102/version/20230530",
