### ISSUE TITLE
Import error: CS kehapiirkond

### ISSUE THREAD

**Issue by marinaivnv** [TEHIK-EE/terminology-migration#29]
Import to **TermX** succeeded: [kehapiirkond](https://termx.kodality.dev/fhir/CodeSystem/kehapiirkond--4?tab=json).

Import to **Ontoserver** errors: 
- The code '113345001' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement
- The code '116007004' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement
- The code '278001007' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement
- The code '416949008' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement
- The code '421060004' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement
- The code '45048000' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement
- The code '51185008' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement
- The code '53120007' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement
- The code '61685007' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement
- The code '69536005' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement
- The code '737561001' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement
- The code '774007' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement
- The code '818983003' is not declared in the base CodeSystem http://snomed.info/sct so is not valid in the supplement

**Comment by rlindstrm** [comment]
In case of CS supplement, version information is expected for the supplemented CS:

"supplements": "http://snomed.info/sct|http://snomed.info/sct/11000181102/version/20230530",

Not ideal, but this way it works.
