### ISSUE TITLE
FHIR profiles for CodeSystem and ValueSet

### ISSUE THREAD

**Issue by rlindstrm** [TEHIK-EE/terminology-migration#3]
These are done under Terminology Services Implementation Guide:

[CodeSystem](https://github.com/TEHIK-EE/TerminologyServices/issues/5)
[ValueSet](https://github.com/TEHIK-EE/TerminologyServices/issues/6)

**Comment by igorboss** [comment]
- Why we need profiles for terminology?
- There are set of standard profiles that may be reused https://www.hl7.org/fhir/valueset-profiles.html, https://www.hl7.org/fhir/codesystem-profiles.html
- May be this topic should be decided after migration done?

**Comment by rlindstrm** [comment]
Profiles are mostly for defining required metadata, and the current plan is to include a lot of it. 
EE terminology profiles will be based on ShareableValueset and ShareableCodesystem at minimum.
