### ISSUE TITLE
Import error: CS radioloogiline-uuring

### ISSUE THREAD

**Issue by marinaivnv** [TEHIK-EE/terminology-migration#30]
Import to **TermX** succeeded: [radioloogiline-uuring](https://termx.kodality.dev/fhir/CodeSystem/radioloogiline-uuring--5?tab=json).

Import to **Ontoserver** errors: 
- The code 'Kõht vaagen +  perfusioon ja spektraal kuvamine' is not valid (whitespace rules)
- The code 'Hüppeliiges  Mortise parem palatis' is not valid (whitespace rules)
- The code 'Hüppeliiges  Mortise vasak palatis' is not valid (whitespace rules)
- The code 'Hüppeliiges  Mortise parem' is not valid (whitespace rules)
- The code 'Hüppeliiges  Mortise vasak' is not valid (whitespace rules)
- The code 'Hüppeliiges  LAT Mortise parem' is not valid (whitespace rules)
- The code 'Hüppeliiges  LAT Mortise vasak' is not valid (whitespace rules)
- The code 'Kandluud  LAT' is not valid (whitespace rules)

**Comment by rlindstrm** [comment]
Property "synonym" has been defined as type "code" instead of type "string". So for each time this property is used, an error is raised, because it does not compute as a code.

```
      "code": "synonym",
      "uri": "http://hl7.org/fhir/concept-properties#synonym",
      "description": "Synonym",
      "type": "code"
```
Change the last row to "type": "string"

```

                {
                  "code": "synonym",
                  "valueCode": "Pea- ja kaelaarteri sulgemine"
                }
```
Change the last row to "valueString": "whatevertext"
