### ISSUE TITLE
Import error: VS andmevaatur-alalised-diagnoosid

### ISSUE THREAD

**Issue by marinaivnv** [TEHIK-EE/terminology-migration#31]
Import from file to TermX error: 

Concept M89.80 is not present in rhk10 CodeSystem

rhk10 $lookup in TermX: [M89.80](https://termx.kodality.dev/fhir/CodeSystem/rhk10/lookup?_code=M89.80) (not found), [M89.8](https://termx.kodality.dev/fhir/CodeSystem/rhk10/lookup?_code=M89.8)

**Comment by rlindstrm** [comment]
20.02.2024 new version published in pubkeskus. Shall be migrated from the new db dump from pubkeskus.

**Comment by igorboss** [comment]
is it possible to do w/o new dump?
