### ISSUE TITLE
Import error: VS radioloogilise-uuringu-liik

### ISSUE THREAD

**Issue by marinaivnv** [TEHIK-EE/terminology-migration#32]
Import from file to TermX error: 
If concepts provided, then code system should be specified.

Supplement or createCs flag should be provided in the import file.

**Comment by rlindstrm** [comment]
Let's try making just a value set based on codesystem Radioloogiline uuring.

**Comment by igorboss** [comment]
Why supplement needed?
There are enriched version of this classifier https://termx.kodality.dev/resources/code-systems/radiology-service/summary. It does not need any supplement.

**Comment by rlindstrm** [comment]
Please retry import as value set based on Radioloogiline Liik (for now, not the enriched one, but official one with our metadata and content).

**Comment by igorboss** [comment]
Kas radioloogia uuringu klassifikaatoris  radioloogia liik peaks olema koodisüsteemina ja mitte tavalisena string tunnusena?
