### ISSUE TITLE
Value Set files missing identifiers 

### ISSUE THREAD

**Issue by johannes-holm** [TEHIK-EE/terminology-migration#35]
Many value set files (xml, json) lack necessary information, like identifiers where the set's OID should be. For many cases OID is present under the Code System files (not always - "anesteesia liigid"), but shouldn't the identifier be accessible from Value Sets as well?

**Comment by rlindstrm** [comment]
OID should be assigned on ValueSet level, not CodeSystem.

For each ValueSet we should have the OID as well as version OID (Igor, see rationale in 23.10.2023 email). 

This should also make it possible to request expansion of valuesets by OIDs: ValueSet/$expand?url=urn:oid:2.16.840.1.113883.1.11.15691 (should be possible with the latest version of Ontoserver, not entirely sure)
