### ISSUE TITLE
Import error: CS kolposkoopia-uuringu-vastus

### ISSUE THREAD

**Issue by marinaivnv** [TEHIK-EE/terminology-migration#38]
Import from file to TermX error:

Target concept and source concepts are the same.

https://raw.githubusercontent.com/TEHIK-EE/terminology-migration/main/pubkeskus/pub-data/files/33518.csv

Kood = C
Vanem_kood = C

**Comment by rlindstrm** [comment]
Updated in GitHub, ready to be migrated.

**Comment by marinaivnv** [comment]
fixed and imported
