### ISSUE TITLE
Import error: CS naba-seisund-lahkumisel

### ISSUE THREAD

**Issue by marinaivnv** [TEHIK-EE/terminology-migration#39]
Import from file to TermX error:

Target concept and source concepts are the same.

https://raw.githubusercontent.com/TEHIK-EE/terminology-migration/main/pubkeskus/pub-data/files/1391.csv

Kood = 2
Vanem_kood = 2

**Comment by rlindstrm** [comment]
16.02.2024 fixed in pubkeskus. New version was not realeased, the file in pubkeskus was simply replaced with a correct one.
Shall be migrated when we get the new dump of pubkeskus db.
