### ISSUE TITLE
Migration of locally coded value sets

### ISSUE THREAD

**Issue by rlindstrm** [TEHIK-EE/terminology-migration#4]
A legacy code list (klassifikaator) has self-made codes, which are not unique across lists. Therefore, each of those old lists is at the same time a value set and a code system.

**For migration:**
- CodeSystem created from legacy list (klassifikaator)
- ValueSet explicitly created that contains everything from the CodeSystem
- OID that has been used for this list will be attached to ValueSet.Identifier (urn:oid style)
- When the legacy list has been recoded with SNOMED CT (or other code system), the ValueSet will have the new version with new codes, and the old CodeSystem is left behind.
- ValueSet and CodeSystem should use the standard TEHIK profiles (shall be defined in Terminology Services IG).

**To decide:**
- Should the old CodeSystem be deprecated?
- It is not decided which metadata will be kept for each value set row. If we have dates for codesystem concept and valueset inclusion, these will probably be the same and repeated in CS as well as VS?

**Comment by igorboss** [comment]
The legacy code systems can be migrate as value sets with contained code system, like this http://hl7.org/fhir/R4B/valueset-example-hierarchical.json.html

**Comment by rlindstrm** [comment]
Contained code systems are not yet supported in Ontoserver, but it is expected to happen next release, and we can try it out in their test server soon.
As for effectivePeriod - the effective time for codesystem or valueset is not a problem. But I would like to have a proper management for valueset content and have more metadata per each row (inclusion date, deprecation date, replaced by...), but I'm not sure how well that would work out. We'll have to discuss in a meeting.

**Comment by rlindstrm** [comment]
That went fast. CSIRO reports that  https://r4.ontoserver.csiro.au/fhir is now running with experimental support for nested CodeSystems.

**Comment by rlindstrm** [comment]
Ontoserver alpha FHIR R5 server (with contained codesystem support) is available for testing on: https://ontoserver-r5.australiaeast.cloudapp.azure.com/fhir
