### ISSUE TITLE
Import error: CS kesksysteemi-veateated

### ISSUE THREAD

**Issue by marinaivnv** [TEHIK-EE/terminology-migration#41]
- The code 'VCERT-001\t' is not valid (whitespace rules)
- The code 'VCERT-002\t' is not valid (whitespace rules)
- The code 'VCERT-004\t' is not valid (whitespace rules)

https://raw.githubusercontent.com/TEHIK-EE/terminology-migration/main/pubkeskus/pub-data/files/10523.csv

**Comment by rlindstrm** [comment]
Corrected file, also containing new entries: https://pub.e-tervis.ee/classifications/Kesks%C3%BCsteemi%20veateated/1 
Is it ok to just replace 10523.csv with this one?

**Comment by igorboss** [comment]
yes
