### ISSUE TITLE
ValueSet concept comment and order

### ISSUE THREAD

**Issue by rlindstrm** [TEHIK-EE/terminology-migration#42]
There is an extension: https://hl7.org/fhir/extensions/StructureDefinition-valueset-concept-comments.html
I think using it would reduce our need for creating code system supplements.

Another extension is https://hl7.org/fhir/extensions/StructureDefinition-valueset-conceptOrder.html
It's something we have not had so far, but in csv the order is often implied by the order of rows. I think we should include the option of having it.

**Comment by igorboss** [comment]
Yes, order and comment in the list of defined properties: https://termx.kodality.dev/resources/defined-properties and may be used.

We should have the order field in the code system first to use order property in the valueset.

**Comment by rlindstrm** [comment]
valueset-concept-comment not reasonable, because only usable for extensionally defined value sets and only in the value set definition part. Not usable in expansion.

conceptOrder - Igor tests how it works and interacts with concept property "order".

**Comment by rlindstrm** [comment]
If order in CS property, expansion works.
If order in VS extension, expansion in TermX didn't work.
In both cases, the expansion should ideally be in the right order, so that regardless of how the order is defined, the users can always rely on the order of appearance. (Rutt will check if this has been done in Ontoserver).

Not going to work on it right now.

**Comment by igorboss** [comment]
>> Not going to work on it right now.
