### ISSUE TITLE
Missing ValueSet metadata

### ISSUE THREAD

**Issue by rlindstrm** [TEHIK-EE/terminology-migration#43]
Description (Column K: description (valueset))
Name (Column H: name)
ChangeManagementDescription (Column M: VS.changeManagement)

**Comment by igorboss** [comment]
Which actions do you suppose?

**Comment by rlindstrm** [comment]
Include in ValueSet migration, because the data exists in the table.

**Comment by rlindstrm** [comment]
Description and Name imported.
What shall we do with ChangeManagementDescription? To discuss/decide.

**Comment by rlindstrm** [comment]
Rutt asks CSIRO how custom extensions work with or break Ontoserver

**Comment by igorboss** [comment]
The current example here https://termx.kodality.dev/fhir/CodeSystem/anamneesi-vanusegrupp--1.0.0. Please check https://build.fhir.org/ig/TEHIK-EE/TerminologyServices/branches/master/StructureDefinition-tehikcodesystem.html - the 
changeManagementDescription and codingPrinciples attributes has same urls of extension "https://fhir.ee/StructureDefinition/guidance-material"
