### ISSUE TITLE
Version OID for ValueSet

### ISSUE THREAD

**Issue by rlindstrm** [TEHIK-EE/terminology-migration#44]
Create Identifier.type value set.
Use Identifier.type for distinguishing entity-level OID from version OID.
If possible, migrate version OIDs to the table and then to TermX.

**Comment by igorboss** [comment]
The possibility to configure version identifiers was added to TermX. As result type is specified for version OIDs.
~~~
  "identifier": [
    {
      "system": "urn:ietf:rfc:3986",
      "value": "urn:oid:1.3.6.1.4.1.28284.6.2.1.82"
    },
    {
      "type": {
        "coding": [
          {
            "code": "version"
          }
        ]
      },
      "system": "urn:ietf:rfc:3986",
      "value": "urn:oid:1.3.6.1.4.1.28284.6.2.1.82.5"
    }
  ],
~~~
Ontoserver accept this syntax. Check -> "id": "radioloogiline-uuring--5"

Column "void" (aka version oid) is added with formula =CONCAT(N10,CONCAT(".", U10)).
As a result, there is a list of classifiers without oid that are visible well.

They should be fixed and reimported:
anesteesia-liigid
anesteesia-riskid
Elustamise käigus ettevõetud elupäästvad protseduurid
Haigused, millega kaasneb absoluutne mittevastavus B-tõendi tervisenõuetele
Haigused, millega kaasneb absoluutne mittevastavus C-tõendi tervisenõuetele
Haigused, millega kaasneb suhteline mittevastavus A-tõendi tervisenõuetele
Haigused, millega kaasneb suhteline mittevastavus B-tõendi tervisenõuetele
Haigused, millega kaasneb suhteline mittevastavus C-tõendi tervisenõuetele
muu-oluline-info
olulised-kirurgilised-protseduurid
olulised-kroonilised-haigused
proovivotu-aeg
Syndimiskoht
SynnituseTulem
SynnituseValutustamine
VastsyndinuAsfyksiaMarkerid
VastsyndinuJaImikuValjaheide
VolitatudTootajaVolituseLiik
