### ISSUE TITLE
Naming conventions for metadata

### ISSUE THREAD

**Issue by rlindstrm** [TEHIK-EE/terminology-migration#5]
Metadata model comes from Terminology Server IG ([issue](https://github.com/TEHIK-EE/TerminologyServices/issues/7)). 
Additional authoring-related naming conventions for urls, identifiers, organisations, etc may apply, and these should be decided before migration to ensure consistency.

**Comment by igorboss** [comment]
-Url. We can use "https://pub.e-tervis.ee/classifications/$name" as url for legacy code systems and value sets. And use new namespaces (https://fhir.ee/$type/$name and https://tehik.ee/fhir/$type/$name) for new terminology resources.
- Identifier. Most of the identifiers described here https://build.fhir.org/ig/HL7EE/ig-ee-base//CodeSystem-ee-identity-system.html.

**Comment by rlindstrm** [comment]
No need to create unresolvable urls for them. All the legacy content has OID identifiers anyway, which we will migrate, so there is a clear link.
Everything (new and old) goes with https://fhir.ee/$type/$id  That seems to be HL7 preferred/default way.

**Comment by rlindstrm** [comment]
Here are the rules: http://build.fhir.org/ig/TEHIK-EE/TerminologyServices/branches/master/metadata.html 
I will put it to test under issue #8 and continue the discussion there.
Closing this one for now.
