### ISSUE TITLE
Expansions should be recalculated at new migration

### ISSUE THREAD

**Issue by rlindstrm** [TEHIK-EE/terminology-migration#54]
Expansions must be automatically renewed after migration. 
Right now, for some value sets the expansion does not reflect the latest migration. I can manually force a new expansion, but I'd prefer not to.
![image](https://github.com/TEHIK-EE/terminology-migration/assets/112903984/61fe431d-2b4c-47bb-bc2c-66e7512c84ea)

It works ok in Ontoserver, because Ontoserver does not store expansions.

**Comment by marinaivnv** [comment]
fixed
