### ISSUE TITLE
ABO veregrupp - includes too many concepts

### ISSUE THREAD

**Issue by rlindstrm** [TEHIK-EE/terminology-migration#56]
Concept 280416009 is no longer in the active value set version, but is migrated as valid. Possibly because it has retirement date, but is marked active in CSV.
We were supposed to have a check at migration to make sure we catch all cases where retirement date exists and status is active. Do we have it? Is it possible that we have more cases like this?

**Comment by igorboss** [comment]
We can search by different patterns using SQL queries and present through a reporting module.

**Comment by marinaivnv** [comment]
@rlindstrm Concept 280416009 was included because in Google Drive table “publitseeritud_loendid” column “map” has only mappings for concept-code and display, so status and retirement date were ignored.

**Comment by rlindstrm** [comment]
Rutt checks all suspect value sets manually, reports/fixes findings.

**Comment by rlindstrm** [comment]
There should be no more cases like this

**Comment by rlindstrm** [comment]
ABO-veregrupp still has the same problem. I fixed the source file in GitHub, should correct it self with next import.

**Comment by marinaivnv** [comment]
@rlindstrm abo-veregrupp--4.0.0 fixed and reimported
