### ISSUE TITLE
Metadata for manually submitted CodeSystems

### ISSUE THREAD

**Issue by rlindstrm** [TEHIK-EE/terminology-migration#57]
OID, version OID, description, author

Incomplete metadata for: RHK10, NCSP, ...

**Comment by igorboss** [comment]
To review using the reporting module and fix manually.

**Comment by rlindstrm** [comment]
Kodality makes report.
Then we review who does manual fixes.

**Comment by marinaivnv** [comment]
[CS_VS_empty_metadata.pdf](https://github.com/TEHIK-EE/terminology-migration/files/14508759/CS_VS_empty_metadata.pdf)
