### ISSUE TITLE
ValueSet SNOMED version needs a change

### ISSUE THREAD

**Issue by rlindstrm** [TEHIK-EE/terminology-migration#58]
Ontoserver was messing up some display names for SNOMED value sets (Radioloogiline staatus; Geeniprodukti funktsioon). I had CSIRO investigate it, and there was a combination of small bugs on both sides.

Here's what we need to do:
1) In our value set, the version in the compose right now is "11000181102"  which is not a valid SNOMED version.  It should be http://snomed.info/sct/11000181102 for the Edition, or http://snomed.info/sct/11000181102/version/20231130  for the full Version.

2) Normally, we would want Edition for the version, but right now, Ontoserver does not work properly this way. So until the bug fix, we should use version http://snomed.info/sct/11000181102/version/20231130

**Comment by marinaivnv** [comment]
Now in TermX it is possible to define CodeSystem version URI. If URI is defined for the version, it will appear instead of version code in FHIR compose. 

URI  http://snomed.info/sct/11000181102/version/20231130 is now defined for the version "11000181102" and reimport to Ontoserver was done.
