### ISSUE TITLE
NCSP

### ISSUE THREAD

**Issue by rlindstrm** [TEHIK-EE/terminology-migration#6]

**Comment by igorboss** [comment]
Does we need conceptMap for https://pub.e-tervis.ee/classifications/NCSP/9/NCSP_2023_muutuste_vastavus.xlsx?

**Comment by rlindstrm** [comment]
Would the previously mentioned problem with randomly floating deprecated codes disappear if we migrated an earlier version and created a conceptmap?
If yes, then let's do it. 
I know it's what you originally proposed, and probably you saw this coming, but I didn't. :)

**Comment by rlindstrm** [comment]
Also, please make: 
1) all display names Estonian.
2) hierarchy expressed with property 'parent' not concepts in concepts.

**Comment by igorboss** [comment]
- New import of NCSP with versions 8 and 9 performed. Initially v8 was imported and then v9. The diff of versions https://termx.kodality.dev/resources/code-systems/compare;code-system=ncsp (select 8 and 9)
- NCSP version 8 contains codes that missing in the version 9. There are no  instruction to invalidate missing codes in v9. For example code "[18660](https://termx.kodality.dev/resources/code-systems/ncsp/concepts/18660/edit)" still active in v8 (that is correct), and missing in [v9](https://termx.kodality.dev/resources/code-systems/ncsp/versions/9/concepts) (may be it is also correct).
- NCSP version 8 is plain (dont have hierarchy) and v9 is hierarchichal. Almost for every concept the new concept version was created. see example https://termx.kodality.dev/resources/code-systems/ncsp/concepts/DQD50/edit. 
- There are no hierarchies for "retired" code, such as [SI110](https://termx.kodality.dev/resources/code-systems/ncsp/versions/9/concepts/SI110/edit). All "retired" codes also still active.
- My proposal is to create v10 and fix migrations issues: a) create missing hierarchies; b) mark retired codes as retired

**Comment by rlindstrm** [comment]
There is an error in the source file. The effectiveUntil date (Kehtivuse lõpu kpv) is correctly marked, but status has remained active. Question is, shall we fix it in pubkeskus before migration or during migration?

**Comment by rlindstrm** [comment]
![image](https://github.com/TEHIK-EE/terminology-migration/assets/112903984/8dd176dc-9f8e-4b6c-a319-1c2119240bfd)

**Comment by igorboss** [comment]
We can fix it during migration. In any case it will be v10 with fixed data, because old published versions are immutable!

**Comment by rlindstrm** [comment]
Fix the file (hierarchy, statuses) in pubkeskus and release new version, which will then be migrated.

**Comment by carmenmae** [comment]
[10 poolik.csv](https://github.com/TEHIK-EE/terminology-migration/files/12458042/10.poolik.csv)
I have attached an excel document. Obsolete codes have updated status and should be fine. However, making this excel table was not 100% successful. I didn't get quite correct parents for all levels. My excel knowledge is unfortunately limited to what I could generate in there formula row. Accordingly, I have not run the result through Snapper either, as I know it is not correct anyway. At the moment, I left the formula in so that if either of you can see what mistakes I made or what I missed.

**Comment by carmenmae** [comment]
[10.csv](https://github.com/TEHIK-EE/terminology-migration/files/12458104/10.csv)

Expired codes have been invalidated.
Despite various attempts, I was unable to get the correct parent code running for all levels. It remained a repeat of the parent of the first level chapter, despite the fact that the rest of the information changed along with it. I left my formula in at the moment so you can give feedback if needed, what was missing/excessive/wrong.

**Comment by igorboss** [comment]
Why to remove? If we remove parents the presemtation of these code will changes very ugly. My proposal to set status to "inactive" for these parent concepts that don't have active concepts. 
We also should follow basic terminology rules and don't change the meaning of the concepts (incl parents)

**Comment by igorboss** [comment]
There are still some concepts withot statuses (typically it is a chapters). But not only chapters, for example EWC*, GDA*, NCK*, NHK*, etc codes

**Comment by carmenmae** [comment]
Yes, certain cells are empty in the excel table (especially regarding the new chapters). I understood from Rutt's story that it was also questionable for her, so I couldn't fix the situation either.

**Comment by carmenmae** [comment]
> There are still some concepts withot statuses (typically it is a chapters). But not only chapters, for example EWC*, GDA*, NCK*, NHK*, etc codes

On one of my computers it shows where no data has been lost from the table and on the other computer it warns that some information has been lost. I will review this part again in the evening.

**Comment by igorboss** [comment]
>> so I couldn't fix the situation either?!

**Comment by carmenmae** [comment]
I implemented the changes.
[10.xlsx](https://github.com/TEHIK-EE/terminology-migration/files/12558387/10.xlsx)

**Comment by rlindstrm** [comment]
I'd like to have a version without concepts in concepts, and just use property "parent". This is how it has been published so far, and it is easy to make it into a flat CSV. I understand it might be annoying for TermX.

**Comment by igorboss** [comment]
You can setup the required behaviour. If you don't need hierarchy, it may be switched off. Just set "Hierarchy meaning" to blank. In this case, you will have a list of concepts with parent property. Or you may have both hierarchy and properties (like I configured just now). For example, https://termx.kodality.dev/fhir/CodeSystem/ncsp--9 -> JSON page.

**Comment by rlindstrm** [comment]
I don't think that's right. 
Property "parent" is for describing the hierarchy, and hierarchy-meaning has to be filled in. 
Otherwise SNOMED would be non-hierarchical, because it defines parents through properties.
I think Ontoserver does not do subsume if hierachy meaning is not set correctly.

**Comment by igorboss** [comment]
Removing the hierarchy is a big issue and a limitation for developers. It means that the developer can not use the resource as is and present it in the application. Instead, they should write the source code in the backend, process the (sometimes huge) file, create a hierarchy and return it to the application. Depending on the file size, it may take several seconds (even more than 10 in the case of icd10). Conversely, we can prepare the hierarchy and the developer may use it AS-IS without any transformation.

**Comment by igorboss** [comment]
@carmenmae please check https://termx.kodality.dev/resources/code-systems/ncsp/versions/10/concepts. It seems almost good. Probably you want to fix Y codes?

**Comment by igorboss** [comment]
@rlindstrm Please look into https://termx.kodality.dev/resources/code-systems/ncsp/versions/10/concepts. Should we  add (to the excel) the property notSelectable=true for chapters?

**Comment by igorboss** [comment]
@carmenmae the file contains data below (the same term). Is it ok? Can you validate other same names (https://termx.kodality.dev/resources/code-systems/validator;code-system=ncsp;version=9905050)?

![image](https://github.com/TEHIK-EE/terminology-migration/assets/4351675/451079c2-d4ed-4214-879c-fd5159363336)

**Comment by igorboss** [comment]
There are some concepts that don't have status. All concepts without status imported with status 'draft'.

**Comment by carmenmae** [comment]
> @carmenmae please check https://termx.kodality.dev/resources/code-systems/ncsp/versions/10/concepts. It seems almost good. Probably you want to fix Y codes?

To be honest, I'm not sure how this topic should be approached. I don't see/can't see how to view Y codes. Maybe you can show me on Monday (I won't be at work tomorrow).

The same applies to the task setup sent as a screenshot. I don't quite understand what I should validate.

Otherwise, as of today, I have viewed the table on Google to the end. There are some places that need to be clarified, to which perhaps a solution/answer will be added in the near future.

**Comment by igorboss** [comment]
They should be under Y chapter like other codes under own character. If you look to Excel you can see that YCA refer YC, but YC (that refer to Y) missing in the Excel. As alternative you can change parent Yxx codes to Y. 
<img width="593" alt="image" src="https://github.com/TEHIK-EE/terminology-migration/assets/4351675/21800b0f-850e-40d7-8b40-bb3fa123429f">

**Comment by rlindstrm** [comment]
We have a new file with many fixes. Shall we try again?

**Comment by igorboss** [comment]
Can you attach or send the new file?

**Comment by kristakaert** [comment]
I am waiting for the owner (Health Insurance Fund) to validate last changes. The meeting for final validation is scheduled on the 15th of March (due to vacation period on their side). After that meeting I'll attach the new and fixed file.
