### ISSUE TITLE
Wrong version - updated in the spreadsheet

### ISSUE THREAD

**Issue by rlindstrm** [TEHIK-EE/terminology-migration#62]
version corrected, marked with status 6:
Antibiootikumtundlikkuse uuringu vastus
CPI indeks
Diagnoosi liik
Diagnoosi statistiline liik
Dokumendi tüüp (DL väline)
Eemaldamise põhjus
ER_Ravikuuritüüp
ER_Retsepti staatused
ER_Soodustuse määr
ER_Ühikud annustamine
ER_Ühikud mahu- ja massiühikud
ER_Ühikud aja
Farmakogeneetilise uuringu (geeniprodukti funktsioon) vastus
Furkatsiooni kahjustuse aste

**Comment by marinaivnv** [comment]
reimport done, old versions deleted from Ontoserver
