### ISSUE TITLE
Updated value sets

### ISSUE THREAD

**Issue by rlindstrm** [TEHIK-EE/terminology-migration#63]
Marked with status 6 in the spreadsheet. Version adjusted when needed. Changes in GitHub.
Apgari kompenendid - added hierarchy according to V2 23.02.2024
Asendamatuse põhjus - added concept according to V4 05.12.2023
ER_Kindlustust tõendava dokumendi liik - added concepts according to V2 23.02.2024
ER_Koondarve tüüp - added/removed concepts according to  V2 23.02.2024
ER_Retsepti kordsus - added concept according to V2 05.12.2023
ER_Retsepti liik - added concept according to V2 05.12.2023
Farmakogeneetilise uuringu (metaboolne aktiivsus) vastus - added cocepts according to V3 30.112023

**Comment by marinaivnv** [comment]
reimport is done, old version deleted from Ontoserver
