### ISSUE TITLE
Order of concepts

### ISSUE THREAD

**Issue by rlindstrm** [TEHIK-EE/terminology-migration#64]
Can it be easily done that the default order of concepts is alphabetical by code or the order they appear in the file. 
For discussion.

https://termx.kodality.dev/resources/value-sets/artikulatsiooniharjumused/versions/1.0.0/summary  For example here, the order is actually meaningful, but it's all scrambled after migration.

**Comment by igorboss** [comment]
The one possibility is use http://hl7.org/fhir/StructureDefinition/codesystem-conceptOrder property that designed for that purpose.

**Comment by rlindstrm** [comment]
It seems to keep the code system order by default. So if we could migrate them in the current csv-published order, it would be ok for now.

**Comment by rlindstrm** [comment]
Here's a funny one:
https://termx.kodality.dev/fhir/ValueSet/immuniseerimise-vanusegrupp--4.0.0

**Comment by igorboss** [comment]
Alphabetic ordering does't help here. Only conceptOrder attribute may work properly

**Comment by rlindstrm** [comment]
Just remembered a side discussion I had:
![image](https://github.com/TEHIK-EE/terminology-migration/assets/112903984/df9364bb-441e-4e34-a167-894e81157e57)

**Comment by marinaivnv** [comment]
Possible solution: I have added new column to spreadsheet called 'conceptOrder'. This column expects values 1 and 0. If value is 1, then import process adds automatic order number for concept (the line number in csv file). Also to get this order info in value set the conceptOrder should be added to column 'VSproperties'. 

Example is done for `immuniseerimise-vanusegrupp`. This CS and VS is also imported to Ontoserver with order information. 

@rlindstrm If this solution suits you, then please make changes to spreadsheet lines where order is required.

**Comment by rlindstrm** [comment]
@marinaivnv Can you quickly test what happens to a hierachical codesystem (nested concepts) when it has concept order as it would be flat.
For example: https://termx.kodality.dev/resources/code-systems/syndimiskoht/versions/2.0.0/concepts

|code|conceptOrder|
|-----|-------|
|1|1|
|2|2|
|3|3|
|31|4|
|32|5|
|4|6|

**Comment by igorboss** [comment]
My advice is to use bigger numbers than 1,2,3. For example, 10,20,30 or 100, 200, 300. It gives the ability to add something in the middle. In this case, 10, 20, 30, 40 are for the first level, and 33, 36 are for the second level of an element, with order 30.

**Comment by igorboss** [comment]
@marinaivnv please add ordering by conceptOrder (at least) in the valueset expansion

**Comment by marinaivnv** [comment]
@igorboss I can add ordering in expansion only in TermX, json files with examples provided above are responses from Ontoserver

**Comment by marinaivnv** [comment]
@rlindstrm CS with conceptOrder are imported, order is done with gap=10
