### ISSUE TITLE
Diagnoosi statistiline liik - short name missing

### ISSUE THREAD

**Issue by rlindstrm** [TEHIK-EE/terminology-migration#65]
Lühinimetus not migrated as synonym. Not sure it's important, but don't understand why.

**Comment by marinaivnv** [comment]
<img width="520" alt="Screenshot 2024-03-11 at 09 27 02" src="https://github.com/TEHIK-EE/terminology-migration/assets/67741294/d60d30af-3237-420f-9d41-8ebac43346d0">

CS 'Diagnoosi statistiline liik' has synonym in properties list.
