### ISSUE TITLE
Delete Haridus CS and VS

### ISSUE THREAD

**Issue by rlindstrm** [TEHIK-EE/terminology-migration#67]
Haridus has been made inactive, so shall not be migrated anymore. 
Please delete the copy from TermX (or remove from pubkeskus space or do something else that would prevent it from going to Ontoserver).
Let me know if I should delete it from Ontoserver manually.

**Comment by marinaivnv** [comment]
Haridus CS and VS is removed from pubkeskus space in TermX and also deleted from Ontoserver.
