### ISSUE TITLE
Kõne taju - gone missing

### ISSUE THREAD

**Issue by rlindstrm** [TEHIK-EE/terminology-migration#69]
https://pub.e-tervis.ee/classifications/K%C3%B5ne%20taju/1 

Can't find it in the spreadsheet or TermX. Can we add it to migration somehow? It's local codesystem+valueset, OIDs visible in the above link.

**Comment by marinaivnv** [comment]
@rlindstrm Can you please add this manually to spreadsheet? It will be easier if we would have all resources that need import in one spreadsheet with all properties defined there.
