### ISSUE TITLE
Piiriülesest andmevahetusest välja jäävad ATC koodid - expansion missing

### ISSUE THREAD

**Issue by rlindstrm** [TEHIK-EE/terminology-migration#72]
Based on ATC-EE, which is not migrated. Definition is there, but expansion does not work. How to fix?

**Comment by marinaivnv** [comment]
I have imported atc-ee into TermX using this file: 
[est-atc.csv](https://github.com/TEHIK-EE/terminology-migration/files/14586627/est-atc.csv)

After TermX import , import to Ontoserver was done. 

Now Piiriülesest andmevahetusest välja jäävad ATC koodid expansion works.
