### ISSUE TITLE
New migration

### ISSUE THREAD

**Issue by rlindstrm** [TEHIK-EE/terminology-migration#73]
I need a new migration from the full spreadsheet.
Things that **must** be updated are marked with status 6.
Things that **can be** updated (but should not have any changes) are marked with 5.
Things that **must not** be migrated are marked with 0.

The result should be a clean space with all the updated resources and nothing else. I will check the results, and then I would like to migrate it to production Ontoserver next week.

Please log or errors. I did a lot of manual fixing, typos and other stupidities are possible.

**Comment by marinaivnv** [comment]
@rlindstrm 
New space `pubkeskus-prod` was created in TermX. All lines with status 5 and 6 imported there and synced to test Ontoserver. No errors occurred. 

https://termx.kodality.dev/spaces/context;s=10786775?resource=code-system
