### ISSUE TITLE
ig-publisher issues

### ISSUE THREAD

**Issue by igorboss** [TEHIK-EE/terminology-migration#74]
When I tried to add CS definition to IG, igpublisher generated the following errors that should be fixed:
1. extension "codesystem-sourceReference" exists w/o value (example below). Don't add this extension if URL missing 
~~~
{
    "url" : "http://hl7.org/fhir/StructureDefinition/codesystem-sourceReference"
},
~~~

2. the full name of the publisher should be shown as publisher name instead of the code (from "publisher" code system). You can check the [example1](https://terminology.hl7.org/ValueSet-v3-AccessMedicalDevice.json.html) or [example2](https://terminology.hl7.org/CodeSystem-v3-snomed-CT.json.html).

3. There are also URL  and id mismatch problem. I will investigate how to solve this problem.

**Comment by rlindstrm** [comment]
This extension is also unclear to me:
"extension": [
        {
            "url": "http://hl7.org/fhir/tools/StructureDefinition/web-source",
            "valueUrl": "https://termx.kodality.dev/fhir/ValueSet/anesteesia-liigid"
        },
        {
            "url": "http://hl7.org/fhir/StructureDefinition/cqf-knowledgeRepresentationLevel",
            "valueCode": "executable"
        }
    ],
    
   Why would we need that? This means our production environment resources would link a dev-environment outside our control.

**Comment by igorboss** [comment]
- web-source should refer to the permanent web link where terminology resource is available as narrative (in our case some Teabekeskus page). It should be configurable.
- cqf-knowledgeRepresentationLevel is required by [ExecutableValueSet profile](http://hl7.org/fhir/R5/executablevalueset.html)

**Comment by rlindstrm** [comment]
websource is not a required data element. I would still remove it, because I don't want production data to point to a dev environment that is not officially in use.

**Comment by igorboss** [comment]
https://github.com/FHIR/fhir-test-cases/blob/master/tx/requirements.md 

> All code systems and value sets SHALL have a web representation that is appropriate for a human to look at. The content on that page MAY be static or active; it is at the discretion of the server to decide what’s on the page, but it SHOULD be more than just the json/xml for the resource (and it isn’t limited to information in the resource either e.g. the server MAY choose to make additional process/provenance/context information available)

> If the server chooses to make them available elsewhere, it SHALL populate the extension http://hl7.org/fhir/tools/StructureDefinition/web-source with a valueUrl where the web view can be found. This SHALL be populated when the CodeSystem and ValueSet are read, and also in any $expand of the value set (just for the root valueset).

**Comment by marinaivnv** [comment]
For now errors with codesystem-sourceReference and publisher are fixed.

**Comment by rlindstrm** [comment]
Ontoserver has a web presentation, and we're working on other UIs and we will have to have a redirect from fhir.ee urls at some point.
I refuse to have link to a dev environment as an official web source. It will never be official websource. It's a temporary location and will not be kept in sync.

**Comment by marinaivnv** [comment]
@rlindstrm web-source extension is now removed from VS and CS definitions, reimport is done and synced to Ontoserver
