### ISSUE TITLE
property name typos

### ISSUE THREAD

**Issue by rlindstrm** [TEHIK-EE/terminology-migration#75]
I found some typos in migrated value sets. Extra whitespaces cause the expansion not to include these properties.  

      "property": [
            "synonym",
            " definition",
            " conceptOrder"
        ]
    }

Example from immuniseerimise-vanusegrupp--4.0.0

**Comment by marinaivnv** [comment]
Typos found in:
- anamneesi-vanusegrupp
- arengu-hindamise-vanusegrupp
- diagnoosi-statistiline-liik
- igemetasku-mootepunktid
- immuniseerimise-korvalnahud
- kasvamise-vanusegrupp
- immuniseerimise-vanusegrupp
- kehapaikme-suunatapsustused
- immuunhistokeemilised-varvingud
- kolposkoopia-uuringu-vastus
- labivaatuse-vanusegrupp
- mikroobi-kogus
- mtk-kesknarvisysteem-glasgow-pittsburgh
- mtk-pupillidiferents
- mtk-ravimi-manustamisviis
- noustamise-vanusegrupp
- pahaloomulise-kasvaja-staadium
- pahaloomulise-kasvaja-levik-tnm-jargi
- radioloogilise-uuringu-tulemus
- residuaaltuumor
- tnm-maaramise-prefiksid
- uuringu-vanusegrupp
- radioloogiline-uuring

Import script improved and also spreadsheet file fixed.
